# Generated by Django 4.0.6 on 2022-07-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.IntegerField(default='unknow')),
                ('habita_en_casa', models.BooleanField(default=True)),
                ('edad', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
