# Generated by Django 4.0.6 on 2022-07-29 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familia_desafio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='familia',
            new_name='Familia_desafio',
        ),
    ]
