# Generated by Django 4.0.6 on 2022-07-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0002_familia_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familia',
            old_name='name',
            new_name='apellido',
        ),
        migrations.RemoveField(
            model_name='familia',
            name='surname',
        ),
        migrations.AddField(
            model_name='familia',
            name='dni',
            field=models.FloatField(default='unknow'),
        ),
        migrations.AddField(
            model_name='familia',
            name='edad',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='familia',
            name='nombre',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
