# Generated by Django 4.0.6 on 2022-07-29 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0003_rename_name_familia_apellido_remove_familia_surname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='dni',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='familia',
            name='habita_en_casa',
            field=models.BooleanField(default=True),
        ),
    ]
